from __future__ import annotations

import functools
import os
from collections import OrderedDict
from collections.abc import Callable
from typing import Any

import torch
import torch.multiprocessing as mp
from torch import distributed as dist


def is_distributed() -> bool:
    """Return whether ``torch.distributed`` is initialized."""
    return dist.is_available() and dist.is_initialized()


def get_world_size() -> int:
    """Return the number of participating processes.

    Returns:
        The distributed world size, or ``1`` when distributed training is
        not active.
    """
    return dist.get_world_size() if is_distributed() else 1


def get_rank() -> int:
    """Return the rank of the current process.

    Returns:
        The process rank, or ``0`` when distributed training is not active.
    """
    return dist.get_rank() if is_distributed() else 0


def get_dist_info() -> tuple[int, int]:
    """Return the current process rank and world size."""
    """Return rank and world size without requiring distributed setup."""
    return get_rank(), get_world_size()


def is_main_process() -> bool:
    """Return whether the current process is rank zero."""
    return get_rank() == 0


def broadcast_object_list(objects: list[Any], src: int = 0) -> None:
    """Broadcast a mutable list of Python objects from one process.

    Args:
        objects: List to broadcast in place. The list must have the same
            length on every process.
        src: Rank of the process that owns the source values.
    """
    if is_distributed():
        dist.broadcast_object_list(objects, src=src)


def collect_results(results: list[Any], size: int) -> list[Any] | None:
    """Collect per-process results and truncate them to a dataset size.

    Args:
        results: Results produced by the current process.
        size: Number of results expected in the final ordered collection.

    Returns:
        The ordered results on rank zero, and ``None`` on other ranks.
    """
    """Collect interleaved per-rank results using public PyTorch APIs."""
    if not is_distributed():
        return results[:size]
    parts: list[list[Any] | None] = [None] * get_world_size()
    dist.all_gather_object(parts, results)
    if not is_main_process():
        return None
    ordered: list[Any] = []
    max_length = max(len(part or []) for part in parts)
    for index in range(max_length):
        for part in parts:
            if part is not None and index < len(part):
                ordered.append(part[index])
    return ordered[:size]


def all_reduce_dict(data: dict[str, torch.Tensor], op: Any = dist.ReduceOp.SUM) -> OrderedDict[str, torch.Tensor]:
    """Reduce a dictionary of tensors across all processes.

    Args:
        data: Mapping from names to tensors. Keys are sorted before reduction.
        op: Reduction operation passed to ``torch.distributed.all_reduce``.

    Returns:
        An ordered dictionary containing reduced tensor copies.
    """
    result = OrderedDict((key, value.clone()) for key, value in sorted(data.items()))
    if is_distributed():
        for value in result.values():
            dist.all_reduce(value, op=op)
    return result


def sync_random_seed(seed: int | None = None) -> int:
    """Synchronize a random seed across all processes.

    Args:
        seed: Seed generated by rank zero. If omitted, rank zero generates
            one from the current process RNG.

    Returns:
        The synchronized seed.
    """
    if seed is None:
        seed = int(torch.randint(0, 2**31, (1,)).item())
    values = [seed]
    broadcast_object_list(values)
    return int(values[0])


def init_dist(launcher: str, backend: str | None = None, **kwargs: Any) -> None:
    """Initialize a PyTorch distributed process group.

    Args:
        launcher: Launcher name. Currently, only ``"pytorch"`` is supported.
        backend: Torch distributed backend. If omitted, selects the backend
            from the active accelerator.
        **kwargs: Additional options forwarded to process-group setup.

    Raises:
        ValueError: If ``launcher`` is unsupported.
    """
    if launcher != "pytorch":
        raise ValueError(f"Invalid launcher type: {launcher}")
    if mp.get_start_method(allow_none=True) is None:
        mp.set_start_method("spawn")

    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    accelerator = torch.accelerator.current_accelerator(check_available=True)
    device = None
    if accelerator is not None:
        requested_device = kwargs.get("device_id", local_rank)
        device = (
            torch.device(accelerator.type, requested_device)
            if isinstance(requested_device, int)
            else torch.device(requested_device)
        )
        torch.accelerator.set_device_index(device)
    if backend is None:
        backend = dist.get_default_backend_for_device(accelerator.type if accelerator is not None else "cpu")
    if device is not None:
        kwargs["device_id"] = device
    dist.init_process_group(backend=backend, **kwargs)


def master_only(func: Callable) -> Callable:
    """Run ``func`` only on rank zero."""

    @functools.wraps(func)
    def wrapper(*args: Any, **kwargs: Any) -> Any:
        if is_main_process():
            return func(*args, **kwargs)
        return None

    return wrapper


def allreduce_params(params: list[torch.nn.Parameter], coalesce: bool = True, bucket_size_mb: int = -1) -> None:
    """Average model parameters across ranks in place."""
    _allreduce_tensors([param.detach() for param in params], coalesce, bucket_size_mb)


def allreduce_grads(params: list[torch.nn.Parameter], coalesce: bool = True, bucket_size_mb: int = -1) -> None:
    """Average available parameter gradients across ranks in place."""
    _allreduce_tensors(
        [param.grad.detach() for param in params if param.requires_grad and param.grad is not None],
        coalesce,
        bucket_size_mb,
    )


def _allreduce_tensors(tensors: list[torch.Tensor], coalesce: bool, bucket_size_mb: int) -> None:
    world_size = get_world_size()
    if world_size == 1 or not tensors:
        return
    if not coalesce:
        for tensor in tensors:
            dist.all_reduce(tensor)
            tensor.div_(world_size)
        return

    buckets: OrderedDict[tuple[torch.device, torch.dtype], list[list[torch.Tensor]]] = OrderedDict()
    limit = bucket_size_mb * 1024 * 1024 if bucket_size_mb > 0 else None
    for tensor in tensors:
        key = (tensor.device, tensor.dtype)
        bucket = buckets.setdefault(key, [[]])[-1]
        size = sum(item.numel() * item.element_size() for item in bucket)
        if limit is not None and bucket and size + tensor.numel() * tensor.element_size() > limit:
            bucket = []
            buckets[key].append(bucket)
        bucket.append(tensor)
    for groups in buckets.values():
        for group in groups:
            dist.all_reduce_coalesced(group)
            for tensor in group:
                tensor.div_(world_size)
